# Site settings
title: Helena Richie
description: Jekyll Theme Minimal Resume
# baseurl: "/helenarichie" # the subpath of your site
# url: "https://helenarichie.github.io/helenarichie" # the base hostname & protocol for your site

# User settings
username: Helena Richie
user_description: I am a fourth-year undergraduate student at the University of Pittsburgh. I am a double major in the Physics & Astronomy and Mathematics departments. I have several years of experience in research in the Physics & Astronomy department. My research interests include observational astronomy and exoplanet detection. Outside of academics I enjoy practicing yoga, playing volleyball, and trying new food!
user_title: Exoplanet Researcher
email: helenarichie@gmail.com
# instagram_username: astrohelena
# github_username:  helenarichie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
