# Site settings
title: Helena Richie
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Helena Richie
user_description: I am a fourth-year undergraduate student in the Physics & Astronomy and Mathematics departments at the University of Pittsburgh. My research is in exoplanet detection as lead undergraduate of the Survey of Tranisitng Extrasolar Planets at the University of Pittsburgh (STEPUP).
I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>crypto-world</b> working for Radix, a London based startup trying to create the next massive scalable DLT.. I'm one of the two guys behind all the JS related stuff. Visit my blog here":" <a href="https://mauriciourraco.com" target="_blank">https://mauriciourraco.com</a>
user_title: Exoplanet Researcher
email: helenarichie@gmail.com
# twitter_username: astr0helena
# github_username:  helenarichie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
