# Site settings
title: Helena Richie
description: Jekyll Theme Minimal Resume
# baseurl: "/helenarichie" # the subpath of your site
# url: "https://helenarichie.github.io/helenarichie" # the base hostname & protocol for your site

# User settings
username: Helena M. Richie
user_description: <p>I am a first-year PhD student at the University of Pittsburgh in the Department of Physics & Astronomy. My interests include observational astronomy and exoplanet detection.</p><p>I earned my B.Sc. in Physics & Astronomy and Mathematics from the University of Pittsburgh in 2020. During my undergrad, I served as Lead Undergraduate of the Survey of Transiting Extrasolar Planets at the University of Pittsburgh (STEPUP), which is an observational astronomy group that uses instruments based out of Pittsburgh's <a href="http://www.pitt.edu/~aobsvtry/" style="color: #5C85D6">Allegheny Observatory</a> to detect transiting exoplanets.</p>
user_title: Graduate Student // Astronomy
email: helenarichie@pitt.edu
# instagram_username: astrohelena
# github_username:  helenarichie

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
